<?php
echo "levelprompt = 0;",
	"game.world.setBounds(0, 0, canvas_x, canvas_y);",
	"level_complete = flag_red.create(game.world.width / 2 - tile_size / 2, game.world.height - tile_size * 2 - 4, 'flag_red');",
	"level_complete.body.immovable = true;",
	"tree = decoration.create(100, game.world.height - tile_size * 4, 'tree');",
	"tree.body.immovable = true;",
	"tree = decoration.create(120, game.world.height - tile_size * 4, 'tree');",
	"tree.body.immovable = true;",
	"tree = decoration.create(160, game.world.height - tile_size * 4, 'tree');",
	"tree.body.immovable = true;",
	"tree = decoration.create(250, game.world.height - tile_size * 4, 'tree');",
	"tree.body.immovable = true;",
	"move_text = game.add.text(50, game.world.height- tile_size * 5, 'Move using the arrow keys', {fill: '#000'}).angle = -6;",
	"jump_text = game.add.text(250, game.world.height- tile_size * 5, 'and jump with \"up\"', {fill: '#000'}).angle = 1;",
	"flag_red_text = game.add.text(450, game.world.height- tile_size * 7, 'Get to the red flag!', {fill: '#000'}).angle = -2;",
	"ledge = platforms.create(600 - tile_size / 4, game.world.height - tile_size * 1.7, 'ground_2');",
	"ledge.body.immovable = true;",
	"tree = decoration.create(600, game.world.height - tile_size * 4.7, 'tree');",
	"tree.body.immovable = true;",
	"title = decoration.create(game.world.width / 2,100, 'title');",
	"title.anchor.setTo(0.5, 0);",
	"title.body.immovable = true;",
	"define_player_location = false;",
	"use_title = true;";
?>
